language: java
sudo: false
dist: trusty

before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - chmod +x gradlew

git:
  depth: false

env:
  global:
    - TERM=dumb
    - JADX_VERSION=$(git describe --abbrev=0 --tags).b$TRAVIS_BUILD_NUMBER.$(git rev-parse --short HEAD)

matrix:
  include:
    - env: JDK=oracle-8
      jdk: oraclejdk8
    - env: JDK=oracle-10
      install: . ./install-jdk.sh -F 10 -L BCL

script:
  - java -version
  - echo "jadx version $JADX_VERSION"
  - sed -i "s/BUILD_VERSION/$JADX_VERSION/g" bintray-unstable.json
  - ./gradlew clean build

after_success:
  - test $JDK = "oracle-8" && ./gradlew clean build jacocoTestReport && bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - test $JDK = "oracle-8" && ./gradlew clean sonarqube -Dsonar.host.url=$SONAR_HOST -Dsonar.organization=$SONAR_ORG -Dsonar.login=$SONAR_TOKEN || echo "Skip sonar build and upload"

before_deploy:
  - ./gradlew clean dist

deploy:
  - provider: bintray
    file: bintray-unstable.json
    user: skylot
    key: $BINTRAY_KEY
    skip_cleanup: true
    on:
      branch: master
      tags: false
      condition: $JDK = oracle-8

  - provider: script
    skip_cleanup: true
    on:
      branch: release
      tags: false
      condition: $JDK = oracle-8
    script: bash scripts/travis-release.sh

notifications:
  email:
    - skylot@gmail.com
